### ISSUE TITLE
DESARROLLO DE CONTRATO DE SOFTWARE

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/Horizon#23]
[Contrato de desarrollo de software.pdf](https://github.com/SistemasTecTlaxiaco/Horizon/files/10180962/Contrato.de.desarrollo.de.software.pdf)

**Comment by Nayee123** [comment]
Buen Trabajo 50%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
